name: publish page
description: does the thing
inputs:
  build_dir:
    description: output directory
    required: false
    default: dist
  target_dir:
    description: deploy directory
    required: false
    default: docs

runs:
  using: docker
  image: Dockerfile
  env:
    BUILD_DIR: ${{ inputs.build_dir }}
    TARGET_DIR: ${{ inputs.target_dir }}
